// hotelFormConfig.js
// hotelFormConfig.js
export const hotelFormConfig = () => ({
  commonFields: [
    {
      name: "nameAr",
      labelAr: "الاسم بالعربية",
      labelEn: "Name (Arabic)",
      type: "text",
      col: 6,
      required: true,
      order: 1,
    },
    {
      name: "nameEn",
      labelAr: "الاسم بالإنجليزية",
      labelEn: "Name (English)",
      type: "text",
      col: 6,
      required: true,
      order: 1,
    },
    {
      name: "descriptionAr",
      labelAr: "الوصف بالعربية",
      labelEn: "Description (Arabic)",
      type: "textarea",
      rows: 3,
      col: 6,
      order: 2,
    },
    {
      name: "descriptionEn",
      labelAr: "الوصف بالإنجليزية",
      labelEn: "Description (English)",
      type: "textarea",
      rows: 3,
      col: 6,
      order: 2,
    },
    {
      name: "stars",
      labelAr: "عدد النجوم",
      labelEn: "Stars",
      type: "select",
      col: 4,
      required: true,
      order: 3,
      options: [
        { value: 1, labelAr: "1 نجم", labelEn: "1 Star" },
        { value: 2, labelAr: "2 نجوم", labelEn: "2 Stars" },
        { value: 3, labelAr: "3 نجوم", labelEn: "3 Stars" },
        { value: 4, labelAr: "4 نجوم", labelEn: "4 Stars" },
        { value: 5, labelAr: "5 نجوم", labelEn: "5 Stars" },
      ],
      defaultValue: 3,
    },
    {
      name: "hotelType",
      labelAr: "نوع الفندق",
      labelEn: "Hotel Type",
      type: "select",
      col: 4,
      required: true,
      options: [
        { value: "hotel", labelAr: "فندق", labelEn: "Hotel" },
        { value: "resort", labelAr: "منتجع", labelEn: "Resort" },
        { value: "apartment", labelAr: "شقق", labelEn: "Apartment" },
        { value: "hostel", labelAr: "هوستل", labelEn: "Hostel" },
        { value: "villa", labelAr: "فيلا", labelEn: "Villa" },
      ],
      defaultValue: "hotel",
      order: 3,
    },

    {
      name: "location.country.ar",
      labelAr: "الدولة (عربي)",
      labelEn: "Country (AR)",
      type: "searchable-select",
      col: 6,
      required: true,
      order: 4,
      defaultValue: "المملكة العربية السعودية",
      optionsSource: "countries",
      syncGroup: "country",
      optionLang: "ar",
    },
    {
      name: "location.country.en",
      labelAr: "الدولة (إنجليزي)",
      labelEn: "Country (EN)",
      type: "searchable-select",
      col: 6,
      required: true,
      order: 4,
      defaultValue: "Saudi Arabia",
      optionsSource: "countries",
      syncGroup: "country",
      optionLang: "en",
    },
    {
      name: "location.country.code",
      type: "hidden",
      defaultValue: "SA",
      order: 4,
    },
    {
      name: "location.city.ar",
      labelAr: "المدينة (عربي)",
      labelEn: "City (AR)",
      type: "text",
      col: 6,
      order: 5,
      defaultValue: "مكة المكرمة",
      // optionsSource: "cities",
      // dependsOn: "location.country.code",
      // syncGroup: "city",
      // optionLang: "ar",
    },
    {
      name: "location.city.en",
      labelAr: "المدينة (إنجليزي)",
      labelEn: "City (EN)",
      type: "text",
      col: 6,
      order: 5,
      defaultValue: "Makkah",
      // optionsSource: "cities",
      // dependsOn: "location.country.code",
      // syncGroup: "city",
      // optionLang: "en",
    },
    // {
    //   name: "location.area",
    //   labelAr: "المنطقة / الحي",
    //   labelEn: "Area",
    //   type: "text",
    //   col: 6,
    //   order: 6,
    // },
    {
      name: "location.address.ar",
      labelAr: "العنوان (عربي)",
      labelEn: "Address (AR)",
      type: "text",
      col: 6,
      order: 7,
    },
    {
      name: "location.address.en",
      labelAr: "العنوان (إنجليزي)",
      labelEn: "Address (EN)",
      type: "text",
      col: 6,
      order: 7,
    },
    {
      name: "location.coordinates.lat",
      labelAr: "خط العرض",
      labelEn: "Latitude",
      type: "number",
      col: 6,
      order: 8,
      defaultValue: 21.3891,
    },
    {
      name: "location.coordinates.lng",
      labelAr: "خط الطول",
      labelEn: "Longitude",
      type: "number",
      col: 6,
      order: 8,
      defaultValue: 39.8262,
    },

    {
      name: "contact.phone",
      labelAr: "رقم الهاتف",
      labelEn: "Phone Number",
      type: "numeric-text",
      col: 6,
      order: 9,
    },
    {
      name: "contact.email",
      labelAr: "البريد الإلكتروني",
      labelEn: "Email",
      type: "email",
      col: 6,
      order: 9,
    },
    {
      name: "contact.website",
      labelAr: "الموقع الإلكتروني",
      labelEn: "Website",
      type: "text",
      col: 6,
      order: 10,
    },
    {
      name: "contact.whatsapp",
      labelAr: "واتساب",
      labelEn: "WhatsApp",
      type: "numeric-text",
      col: 6,
      order: 10,
    },

    {
      name: "facilities",
      labelAr: "السمات",
      labelEn: "Facilities",
      type: "checkbox-group",
      col: 12,
      options: [
        { key: "wifi", labelAr: "واي فاي", labelEn: "WiFi" },
        { key: "pool", labelAr: "مسبح", labelEn: "Swimming Pool" },
        { key: "restaurant", labelAr: "مطعم", labelEn: "Restaurant" },
        { key: "gym", labelAr: "جيم", labelEn: "Fitness Center" },
        { key: "spa", labelAr: "سبا", labelEn: "Spa" },
        { key: "parking", labelAr: "مواقف سيارات", labelEn: "Parking" },
        { key: "roomService", labelAr: "خدمة الغرف", labelEn: "Room Service" },
      ],
      order: 11,
    },

    {
      name: "images",
      labelAr: "صور الفندق",
      labelEn: "Hotel Images",
      type: "file",
      multiple: true,
      col: 12,
      order: 12,
    },
    {
      name: "attachments",
      labelAr: "الملفات المرفقة (عقود، صور إضافية...)",
      labelEn: "Attachments (Contracts, extra photos...)",
      type: "file-attachment",
      col: 12,
      multiple: true,
      maxFiles: 8,
      maxSizeMB: 15,
    },
    {
      name: "isActive",
      labelAr: "نشط",
      labelEn: "Active",
      type: "checkbox",
      col: 6,
      defaultValue: true,
      order: 13,
    },
    // {
    //   name: "isFeatured",
    //   labelAr: "مميز",
    //   labelEn: "Featured",
    //   type: "checkbox",
    //   col: 6,
    //   defaultValue: false,
    //   order: 13,
    // },
  ],
});
