import { CURRENCY_OPTIONS, DEFAULT_CURRENCY } from "../../../../constants/currencies";

export const bankAccountFormConfig = () => {
  return {
    commonFields: [
      {
        name: "bankNameAr",
        labelAr: "اسم البنك بالعربية",
        labelEn: "Bank Name Arabic",
        type: "text",
        col: 6,
        required: true,
        order: 1,
      },
      {
        name: "bankNameEn",
        labelAr: "اسم البنك بالإنجليزية",
        labelEn: "Bank Name English",
        type: "text",
        col: 6,
        order: 1,
      },
      {
        name: "accountNameAr",
        labelAr: "اسم الحساب بالعربية",
        labelEn: "Account Name Arabic",
        type: "text",
        col: 6,
        required: true,
        order: 2,
      },
      {
        name: "accountNameEn",
        labelAr: "اسم الحساب بالإنجليزية",
        labelEn: "Account Name English",
        type: "text",
        col: 6,
        order: 2,
      },
      {
        name: "beneficiaryName",
        labelAr: "اسم المستفيد",
        labelEn: "Beneficiary Name",
        type: "text",
        col: 6,
        order: 3,
      },
      {
        name: "accountNumber",
        labelAr: "رقم الحساب",
        labelEn: "Account Number",
        type: "text",
        col: 6,
        order: 3,
      },
      {
        name: "iban",
        labelAr: "رقم الآيبان",
        labelEn: "IBAN",
        type: "text",
        col: 6,
        required: true,
        placeholder: "SA03...",
        order: 4,
      },
      {
        name: "swiftCode",
        labelAr: "رمز SWIFT / BIC",
        labelEn: "SWIFT / BIC",
        type: "text",
        col: 6,
        order: 4,
      },
      {
        name: "currency",
        labelAr: "العملة",
        labelEn: "Currency",
        type: "select",
        col: 6,
        required: true,
        defaultValue: DEFAULT_CURRENCY,
        order: 5,
        options: CURRENCY_OPTIONS,
      },
      {
        name: "sortOrder",
        labelAr: "ترتيب العرض",
        labelEn: "Sort Order",
        type: "number",
        col: 6,
        min: 0,
        defaultValue: 0,
        order: 5,
      },
      {
        name: "logo",
        labelAr: "رابط شعار البنك",
        labelEn: "Bank Logo URL",
        type: "text",
        col: 12,
        order: 6,
      },
      {
        name: "notesAr",
        labelAr: "تعليمات التحويل بالعربية",
        labelEn: "Arabic Transfer Instructions",
        type: "textarea",
        rows: 3,
        col: 6,
        order: 7,
      },
      {
        name: "notesEn",
        labelAr: "تعليمات التحويل بالإنجليزية",
        labelEn: "English Transfer Instructions",
        type: "textarea",
        rows: 3,
        col: 6,
        order: 7,
      },
      {
        name: "isActive",
        labelAr: "الحساب مفعل",
        labelEn: "Active",
        type: "checkbox",
        col: 4,
        defaultValue: true,
        order: 8,
      },
      {
        name: "isPublic",
        labelAr: "ظاهر للعملاء",
        labelEn: "Visible to Customers",
        type: "checkbox",
        col: 4,
        defaultValue: true,
        order: 8,
      },
      {
        name: "isDefault",
        labelAr: "الحساب الافتراضي",
        labelEn: "Default Account",
        type: "checkbox",
        col: 4,
        defaultValue: false,
        order: 8,
      },
    ],
  };
};
