export const vehicleRentalFormConfig = (transports = []) => ({
  commonFields: [
    {
      name: "transport",
      labelAr: "وسيلة النقل",
      labelEn: "Transport Vehicle",
      type: "select",
      col: 6,
      required: true,
      order: 4,
      options: transports.map((item) => ({
        value: item._id,
        labelAr: `${item.nameAr} - ${item.capacity || 0} راكب`,
        labelEn: `${item.nameEn} - ${item.capacity || 0} seats`,
      })),
    },
    {
      name: "nameAr",
      labelAr: "اسم عرض التأجير بالعربية",
      labelEn: "Rental Name Arabic",
      type: "text",
      col: 6,
      required: true,
      order: 1,
    },
    {
      name: "nameEn",
      labelAr: "اسم عرض التأجير بالإنجليزية",
      labelEn: "Rental Name English",
      type: "text",
      col: 6,
      required: true,
      order: 2,
    },
    {
      name: "rentalType",
      labelAr: "نوع التأجير",
      labelEn: "Rental Type",
      type: "select",
      col: 6,
      required: true,
      defaultValue: "daily",
      order: 3,
      options: [
        { value: "hourly", labelAr: "بالساعة", labelEn: "Hourly" },
        { value: "daily", labelAr: "باليوم", labelEn: "Daily" },
        { value: "monthly", labelAr: "بالشهر", labelEn: "Monthly" },
        { value: "yearly", labelAr: "بالسنة", labelEn: "Yearly" },
        { value: "trip", labelAr: "بالرحلة", labelEn: "Per Trip" },
      ],
    },
    {
      name: "pricing.basePrice",
      labelAr: "السعر الأساسي",
      labelEn: "Base Price",
      type: "number",
      col: 6,
      required: true,
      order: 4,
    },
    {
      name: "pricing.currency",
      labelAr: "العملة",
      labelEn: "Currency",
      type: "select",
      col: 6,
      defaultValue: "SAR",
      order: 5,
      options: [
        { value: "SAR", labelAr: "ريال سعودي", labelEn: "SAR" },
        { value: "USD", labelAr: "دولار", labelEn: "USD" },
      ],
    },
    {
      name: "isAlwaysAvailable",
      labelAr: "دائم التوفر",
      labelEn: "Always Available",
      type: "checkbox",
      col: 4,
      defaultValue: false,
      order: 6,
    },
    {
      name: "isActive",
      labelAr: "نشط",
      labelEn: "Active",
      type: "checkbox",
      col: 4,
      defaultValue: true,
      order: 7,
    },
  ],
});