export const extraServiceFormConfig = () => ({
  commonFields: [
    {
      name: "nameAr",
      labelAr: "اسم الخدمة بالعربية",
      labelEn: "Arabic Service Name",
      type: "text",
      col: 6,
      required: true,
      order: 1,
    },
    {
      name: "nameEn",
      labelAr: "اسم الخدمة بالإنجليزية",
      labelEn: "English Service Name",
      type: "text",
      col: 6,
      required: true,
      order: 1,
    },
    {
      name: "descriptionAr",
      labelAr: "الوصف بالعربية",
      labelEn: "Arabic Description",
      type: "textarea",
      rows: 3,
      col: 6,
      order: 2,
    },
    {
      name: "descriptionEn",
      labelAr: "الوصف بالإنجليزية",
      labelEn: "English Description",
      type: "textarea",
      rows: 3,
      col: 6,
      order: 2,
    },
    {
      name: "category",
      labelAr: "تصنيف الخدمة",
      labelEn: "Service Category",
      type: "select",
      col: 4,
      required: true,
      defaultValue: "other",
      order: 3,
      options: [
        { value: "airport_service", labelAr: "خدمة مطار", labelEn: "Airport Service" },
        { value: "insurance", labelAr: "تأمين", labelEn: "Insurance" },
        { value: "meal", labelAr: "وجبات", labelEn: "Meals" },
        { value: "religious_guide", labelAr: "إرشاد ديني", labelEn: "Religious Guide" },
        { value: "vip_service", labelAr: "خدمة VIP", labelEn: "VIP Service" },
        { value: "sim_card", labelAr: "شريحة اتصال", labelEn: "SIM Card" },
        { value: "wheelchair", labelAr: "كرسي متحرك", labelEn: "Wheelchair" },
        { value: "other", labelAr: "أخرى", labelEn: "Other" },
      ],
    },
    {
      name: "pricing.basePrice",
      labelAr: "السعر الأساسي",
      labelEn: "Base Price",
      type: "number",
      col: 4,
      required: true,
      min: 0,
      order: 4,
    },
    {
      name: "pricing.currency",
      labelAr: "العملة",
      labelEn: "Currency",
      type: "select",
      col: 4,
      defaultValue: "SAR",
      order: 4,
      options: [
        { value: "SAR", labelAr: "ريال سعودي", labelEn: "SAR" },
        { value: "USD", labelAr: "دولار", labelEn: "USD" },
      ],
    },
    {
      name: "isAlwaysAvailable",
      labelAr: "متاحة دائمًا بدون مخزون",
      labelEn: "Always Available Without Inventory",
      type: "checkbox",
      col: 6,
      defaultValue: true,
      order: 5,
    },
    {
      name: "isActive",
      labelAr: "نشط",
      labelEn: "Active",
      type: "checkbox",
      col: 6,
      defaultValue: true,
      order: 5,
    },
    {
      name: "images",
      labelAr: "صور الخدمة",
      labelEn: "Service Images",
      type: "file",
      col: 12,
      multiple: true,
      order: 6,
    },
  ],
});
