export const PAYMENT_TRANSACTION_STATUS = {

    INITIATED: "INITIATED",

    PENDING: "PENDING",

    PENDING_REVIEW: "PENDING_REVIEW",

    PROCESSING: "PROCESSING",

    AUTHORIZED: "AUTHORIZED",

    CAPTURED: "CAPTURED",

    SUCCESS: "SUCCESS",

    FAILED: "FAILED",

    CANCELED: "CANCELED",

    EXPIRED: "EXPIRED",

    REFUNDED: "REFUNDED",

};