export const publicBookingFormConfig = () => ({
  customerFields: [
    {
      name: "customer.name",
      labelAr: "اسم العميل",
      labelEn: "Customer Name",
      type: "text",
      col: 6,
      required: true,
      order: 1,
    },
    {
      name: "customer.phone",
      labelAr: "رقم الجوال",
      labelEn: "Phone Number",
      type: "text",
      col: 6,
      required: true,
      order: 1,
    },
    {
      name: "customer.email",
      labelAr: "البريد الإلكتروني",
      labelEn: "Email",
      type: "email",
      col: 6,
      order: 2,
    },
    {
      name: "customer.nationality",
      labelAr: "الجنسية",
      labelEn: "Nationality",
      type: "text",
      col: 6,
      order: 2,
    },
  ],

  travelerFields: [
    {
      name: "fullName",
      labelAr: "الاسم الكامل",
      labelEn: "Full Name",
      type: "text",
      col: 6,
      required: true,
      order: 1,
    },
    {
      name: "passportNumber",
      labelAr: "رقم الجواز",
      labelEn: "Passport Number",
      type: "text",
      col: 6,
      order: 1,
    },
    {
      name: "nationality",
      labelAr: "الجنسية",
      labelEn: "Nationality",
      type: "text",
      col: 6,
      order: 2,
    },
    {
      name: "birthDate",
      labelAr: "تاريخ الميلاد",
      labelEn: "Birth Date",
      type: "date",
      col: 6,
      order: 2,
    },
    {
      name: "gender",
      labelAr: "الجنس",
      labelEn: "Gender",
      type: "select",
      col: 6,
      defaultValue: "male",
      order: 3,
      options: [
        { value: "male", labelAr: "ذكر", labelEn: "Male" },
        { value: "female", labelAr: "أنثى", labelEn: "Female" },
      ],
    },
  ],
});