export const umrahProgramFormConfig = () => ({
  commonFields: [
    {
      name: "nameAr",
      labelAr: "اسم البرنامج بالعربية",
      labelEn: "Program Name Arabic",
      type: "text",
      col: 6,
      required: true,
      order: 1,
    },
    {
      name: "nameEn",
      labelAr: "اسم البرنامج بالإنجليزية",
      labelEn: "Program Name English",
      type: "text",
      col: 6,
      required: true,
      order: 1,
    },
    {
      name: "descriptionAr",
      labelAr: "الوصف بالعربية",
      labelEn: "Arabic Description",
      type: "textarea",
      rows: 3,
      col: 6,
      order: 2,
    },
    {
      name: "descriptionEn",
      labelAr: "الوصف بالإنجليزية",
      labelEn: "English Description",
      type: "textarea",
      rows: 3,
      col: 6,
      order: 2,
    },
    {
      name: "startDate",
      labelAr: "تاريخ البداية",
      labelEn: "Start Date",
      type: "date",
      col: 4,
      required: true,
      order: 3,
    },
    {
      name: "endDate",
      labelAr: "تاريخ النهاية",
      labelEn: "End Date",
      type: "date",
      col: 4,
      required: true,
      order: 3,
    },
    {
      name: "durationDays",
      labelAr: "عدد الأيام",
      labelEn: "Duration Days",
      type: "number",
      col: 4,
      min: 1,
      required: true,
      order: 3,
    },
    {
      name: "pricing.basePrice",
      labelAr: "السعر الأساسي",
      labelEn: "Base Price",
      type: "number",
      col: 4,
      min: 0,
      required: true,
      order: 4,
    },
    {
      name: "pricing.currency",
      labelAr: "العملة",
      labelEn: "Currency",
      type: "select",
      col: 4,
      defaultValue: "SAR",
      order: 4,
      options: [
        { value: "SAR", labelAr: "ريال سعودي", labelEn: "SAR" },
        { value: "USD", labelAr: "دولار", labelEn: "USD" },
      ],
    },
    {
      name: "capacity.totalSeats",
      labelAr: "إجمالي المقاعد",
      labelEn: "Total Seats",
      type: "number",
      col: 4,
      min: 1,
      required: true,
      order: 5,
    },
    {
      name: "capacity.availableSeats",
      labelAr: "المقاعد المتاحة",
      labelEn: "Available Seats",
      type: "number",
      col: 4,
      min: 0,
      order: 5,
    },
    {
      name: "isActive",
      labelAr: "نشط",
      labelEn: "Active",
      type: "checkbox",
      col: 4,
      defaultValue: true,
      order: 6,
    },
    {
      name: "images",
      labelAr: "صور البرنامج",
      labelEn: "Program Images",
      type: "image",
      col: 12,
      multiple: true,
      order: 7,
    },
  ],
});